### ISSUE TITLE
Error: "output" for "assets" group in theme "oro" is not defined

### ISSUE THREAD

**Issue by simoncarre** [oroinc/platform#989]
**Summary**  

Hello!
I just updated an OroPlatform project from version 2.6.30 to 3.1.19.
I followed documentation here: https://doc.oroinc.com/backend/setup/upgrade-to-new-version/

But I have issue with command `php bin/console oro:assets:build` that generate this error: 

```
In OroAssetsBuildCommand.php line 179:
                                                                               
  /var/www/aslv-extranet/src/vendor/oro/platform/build/node_modules/webpack-c  
  li/bin/cli.js:93                                                             
  				throw err;                                                               
  				^                                                                        
                                                                               
  Error: "output" for "assets" group in theme "oro" is not defined             
      at StyleLoader.getThemeEntryPoints (/var/www/aslv-extranet/src/vendor/o  
  ro/platform/build/webpack-config-builder/style-loader.js:34:27)              
      at ConfigBuilder._getEntryPoints (/var/www/aslv-extranet/src/vendor/oro  
  /platform/build/webpack-config-builder/oro-webpack-config.js:215:39)         
      at /var/www/aslv-extranet/src/vendor/oro/platform/build/webpack-config-  
  builder/oro-webpack-config.js:83:29                                          
      at handleFunction (/var/www/aslv-extranet/src/vendor/oro/platform/build  
  /node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)                 
      at prepareOptions (/var/www/aslv-extranet/src/vendor/oro/platform/build  
  /node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)                   
      at requireConfig (/var/www/aslv-extranet/src/vendor/oro/platform/build/  
  node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)                   
      at /var/www/aslv-extranet/src/vendor/oro/platform/build/node_modules/we  
  bpack-cli/bin/utils/convert-argv.js:123:17                                   
      at Array.forEach (<anonymous>)                                           
      at module.exports (/var/www/aslv-extranet/src/vendor/oro/platform/build  
  /node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)                  
      at yargs.parse (/var/www/aslv-extranet/src/vendor/oro/platform/build/no  
  de_modules/webpack-cli/bin/cli.js:71:45)                                     
      at Object.parse (/var/www/aslv-extranet/src/vendor/oro/platform/build/n  
  ode_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)                  
      at /var/www/aslv-extranet/src/vendor/oro/platform/build/node_modules/we  
  bpack-cli/bin/cli.js:49:8                                                    
      at Object.<anonymous> (/var/www/aslv-extranet/src/vendor/oro/platform/b  
  uild/node_modules/webpack-cli/bin/cli.js:366:3)                              
      at Module._compile (internal/modules/cjs/loader.js:778:30)               
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10  
  )                                                                            
      at Module.load (internal/modules/cjs/loader.js:653:32)                   
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)                 
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)          
      at Module.require (internal/modules/cjs/loader.js:692:17)                
      at require (internal/modules/cjs/helpers.js:25:18)                       
      at Object.<anonymous> (/var/www/aslv-extranet/src/vendor/oro/platform/b  
  uild/node_modules/webpack/bin/webpack.js:156:2)                              
      at Module._compile (internal/modules/cjs/loader.js:778:30)               
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10  
  )                                                                            
      at Module.load (internal/modules/cjs/loader.js:653:32)                   
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)                 
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)          
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)       
      at startup (internal/bootstrap/node.js:283:19)                           
      at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
Does someone have an idea?

Thank you in advance!

**Details about your environment**
- OroPlatform version: 3.1.19
- PHP version: 7.3.14
- Database (MySQL, PostgreSQL) version : MariaDB 10.1
- Server operating system (Windows, Ubuntu, CentOS, RHEL, Fedora, other Linux OS) version and bitness (32-bit, 64-bit) : Debian Stretch
- NodeJS version: v10.19.0
- Npm version: 6.13.4

**Comment by simoncarre** [comment]
Sorry, issue in a custom `assets.yml` file.

Fixed.

**Comment by anyt** [comment]
For everyone who will struggle with the same issue, here are the documentation links with the guide on how to fix:
- https://doc.oroinc.com/master/backend/bundles/platform/AssetBundle/#error-output-for-assets-group-in-theme-oro-is-not-defined
- https://github.com/oroinc/platform/blob/master/CHANGELOG.md#assetbundle-2
